export const QUESTION_POOL = {
  sp_focused_easy: [
    {q:'What does EEE stand for?',l:'Electrical & Electronic Engineering',r:'Environmental & Energy Engineering',c:'left'},
    {q:'How many schools are there in Singapore Polytechnic?',l:'10 schools',r:'6 schools',c:'left'},
    {q:'Which year was SP founded?',l:'1954',r:'1972',c:'left'},
    {q:'Which school in SP focuses on engineering and technology?',l:'School of EEE',r:'School of Business',c:'left'},
    {q:'True or False: SP has robotics-related CCAs.',l:'True',r:'False',c:'left'},
    {q:'Which is more common in SP?',l:'Hands-on projects',r:'Only lectures',c:'left'},
    {q:'True or False: SP students work on real-world projects.',l:'True',r:'False',c:'left'},
    {q:'Which facility would engineering students use more?',l:'Labs',r:'Sports hall',c:'left'},
    {q:'Which event lets students explore SP courses?',l:'Open House',r:'Graduation Day',c:'left'},
    {q:'True or False: SP offers internships.',l:'True',r:'False',c:'left'},
    {q:'Which is part of student life in SP?',l:'CCAs and competitions',r:'Only exams',c:'left'},
    {q:'What does SP stand for?',l:'Singapore Polytechnic',r:'Science Polytechnic',c:'left'},
    {q:'Which polytechnic is the oldest in Singapore?',l:'Singapore Polytechnic',r:'Temasek Polytechnic',c:'left'},
    {q:'Which activity is common in SP?',l:'Hackathons',r:'Farming lessons',c:'left'},
    {q:'True or False: Polytechnic students can go to university.',l:'True',r:'False',c:'left'},
    {q:'Which skill is important in EEE?',l:'Problem solving',r:'Memorising only',c:'left'},
    {q:'Which environment best describes SP engineering?',l:'Hands-on',r:'Theory only',c:'left'},
    {q:'Which is commonly used in SP learning?',l:'Team projects',r:'Only textbooks',c:'left'},
    {q:'Which event showcases student projects?',l:'Open House',r:'Sports Day',c:'left'},
    {q:'True or False: SP students can join overseas programmes.',l:'True',r:'False',c:'left'},
  ],
  sp_focused_hard: [
    {q:'How many diplomas are offered under SP EEE?',l:'5 diplomas',r:'2 diplomas',c:'left'},
    {q:'Which school color is associated with SP?',l:'Red',r:'Purple',c:'left'},
    {q:'Approximately how many students study at SP?',l:'15,000',r:'3,000',c:'left'},
    {q:'True or False: EEE only involves electrical wiring.',l:'False',r:'True',c:'left'},
    {q:'Which SP area would most likely involve robotics and AI?',l:'Engineering diplomas',r:'Hospitality courses',c:'left'},
    {q:'Which SP school best suits electronics and coding?',l:'EEE',r:'MAD',c:'left'},
    {q:'What can students gain besides grades?',l:'Industry experience',r:'Longer holidays',c:'left'},
    {q:'Which SP school focuses on smart systems and electronics?',l:'EEE',r:'SBA',c:'left'},
    {q:'Which pathway can SP graduates pursue after graduation?',l:'University',r:'Primary school',c:'left'},
    {q:'True or False: SP students may work with industry partners.',l:'True',r:'False',c:'left'},
    {q:'Which is more likely in EEE?',l:'Building prototypes',r:'Cooking classes',c:'left'},
    {q:'Which SP programme exposes students to workplaces?',l:'Internships',r:'Detention',c:'left'},
    {q:'Which is a key focus of EEE?',l:'Technology innovation',r:'Marine biology',c:'left'},
    {q:'Which SP school is linked to AI and embedded systems?',l:'EEE',r:'CLS',c:'left'},
    {q:'True or False: EEE students may learn coding.',l:'True',r:'False',c:'left'},
  ],
  tech_focused_easy: [
    {q:'What does AI stand for?',l:'Artificial Intelligence',r:'Automated Internet',c:'left'},
    {q:'Which is faster?',l:'Wi‑Fi',r:'Bluetooth',c:'left'},
    {q:'Which energy source is renewable?',l:'Solar',r:'Coal',c:'left'},
    {q:'What does IoT stand for?',l:'Internet of Things',r:'Integration of Technology',c:'left'},
    {q:'True or False: Coding is used in engineering.',l:'True',r:'False',c:'left'},
    {q:'True or False: Robotics combines hardware and software.',l:'True',r:'False',c:'left'},
    {q:'Which company is known for electric vehicles?',l:'Tesla',r:'Nokia',c:'left'},
    {q:'Which uses more electricity?',l:'Air conditioner',r:'LED bulb',c:'left'},
    {q:'What does WWW stand for?',l:'World Wide Web',r:'Wireless World Web',c:'left'},
    {q:'Which part of a computer is considered the brain?',l:'CPU',r:'Keyboard',c:'left'},
    {q:'Which invention came first?',l:'Telephone',r:'Smartphone',c:'left'},
    {q:'Which is an example of smart technology?',l:'Smart traffic lights',r:'Regular broom',c:'left'},
    {q:'True or False: Engineering involves creativity.',l:'True',r:'False',c:'left'},
    {q:'Which technology is important for self-driving cars?',l:'Sensors',r:'Typewriters',c:'left'},
    {q:'Which device stores photos and apps?',l:'Smartphone',r:'Stapler',c:'left'},
    {q:'Which gadget connects devices wirelessly?',l:'Bluetooth',r:'Paper clip',c:'left'},
    {q:'Which uses electricity?',l:'Laptop',r:'Notebook',c:'left'},
    {q:'Which field involves protecting passwords and data?',l:'Cybersecurity',r:'Gardening',c:'left'},
    {q:'True or False: Solar panels produce electricity.',l:'True',r:'False',c:'left'},
    {q:'Which device is used for gaming?',l:'Console',r:'Toaster',c:'left'},
  ],
  tech_focused_hard: [
    {q:'Which is older?',l:'The internet',r:'Smartphones',c:'left'},
    {q:'True or False: Engineers help create MRT systems.',l:'True',r:'False',c:'left'},
    {q:'Which device uses more sensors?',l:'Smartphone',r:'Notebook',c:'left'},
    {q:'Which industry uses AI more today?',l:'Both healthcare and entertainment',r:'Neither',c:'left'},
    {q:'Which component stores electricity?',l:'Capacitor',r:'Resistor',c:'left'},
    {q:'Which technology is commonly used in smart homes?',l:'IoT systems',r:'Film cameras',c:'left'},
    {q:'What is the main function of a microchip?',l:'Process information',r:'Store paper documents',c:'left'},
    {q:'True or False: Engineers work in game development.',l:'True',r:'False',c:'left'},
    {q:'Which field focuses on protecting data?',l:'Cybersecurity',r:'Animation',c:'left'},
    {q:'Which communication technology came first?',l:'4G',r:'5G',c:'left'},
    {q:'True or False: Renewable energy engineering is growing.',l:'True',r:'False',c:'left'},
    {q:'Which is an example of automation?',l:'Self-checkout kiosk',r:'Paper map',c:'left'},
    {q:'Which device contains more sensors?',l:'Smartphone',r:'Calculator',c:'left'},
    {q:'True or False: Engineers help design theme park rides.',l:'True',r:'False',c:'left'},
    {q:'Which country created the Shinkansen?',l:'Japan',r:'Australia',c:'left'},
    {q:'Which comes first in product creation?',l:'Idea',r:'Manufacturing',c:'left'},
    {q:'Which technology enables facial recognition?',l:'AI',r:'Flash drives',c:'left'},
    {q:'True or False: Engineers improve healthcare technology.',l:'True',r:'False',c:'left'},
    {q:'Which uses coding more?',l:'AI chatbot',r:'Paper notebook',c:'left'},
    {q:'What does USB stand for?',l:'Universal Serial Bus',r:'Unified System Board',c:'left'},
    {q:'Which engineering branch works most with electronics?',l:'EEE',r:'Marine Biology',c:'left'},
    {q:'Which is commonly used for portable charging?',l:'Power bank',r:'Desktop PSU',c:'left'},
    {q:'Which device converts sunlight into electricity?',l:'Solar panel',r:'Speaker',c:'left'},
    {q:'Which engineering field links to clean energy?',l:'Renewable Energy Engineering',r:'Fashion Design',c:'left'},
    {q:'True or False: Engineers can work in esports and gaming.',l:'True',r:'False',c:'left'},
    {q:'Which device helps detect movement in smart systems?',l:'Motion sensor',r:'Pencil',c:'left'},
    {q:'Which network technology powers mobile internet?',l:'5G',r:'FM radio',c:'left'},
    {q:'Which component controls electrical current?',l:'Resistor',r:'Plastic ruler',c:'left'},
    {q:'Which technology is used in contactless payment?',l:'NFC',r:'CD player',c:'left'},
    {q:'Which field focuses on robots and automation?',l:'Mechatronics',r:'Cooking',c:'left'},
  ],
};